version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama  # persiste modelos

  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_pass
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: rag_api
    restart: unless-stopped
    depends_on:
      - ollama
      - postgres
    ports:
      - "8000:8000"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui
    restart: unless-stopped
    ports:
      - "3000:8080"  # Porta padrão do Open WebUI
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - RAG_API_URL=http://api:8000  # URL da nossa API RAG
    depends_on:
      - ollama
      - api
